name: CI

on:
  pull_request:
    branches: [ main, dev ]
  push:
    branches: [ main, dev ]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  # Non-blocking integrity check for the Gradle wrapper
  wrapper-validation:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4
        continue-on-error: true

  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 21 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          # Optional: writes build scans URL to the job summary when enabled
          # build-scan-publish: true
          cache-read-only: false

      - name: Print tool versions
        run: |
          java -version
          ./gradlew -v

      # Style checks first so failures are fast
      - name: Spotless (check only)
        run: ./gradlew spotlessCheck --no-daemon

      - name: Checkstyle (main + test)
        run: ./gradlew checkstyleMain checkstyleTest --no-daemon

      - name: Build & unit tests
        run: ./gradlew clean build --no-daemon

      # Always publish reports if something failed
      - name: Upload test reports (if failed)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            **/build/test-results/test/*.xml
            **/build/reports/tests/test/**
            **/build/reports/checkstyle/**
            **/build/reports/spotless/**
          if-no-files-found: ignore
